### ISSUE TITLE
Adding more options to tools/pinyin

### ISSUE THREAD

**Issue by suntong** [go-ego/gpy#14]
- Ego version (or commit ref): `v0.40.0`
- Go version: `go1.14.3`
- Gcc version: `gcc version 9.3.0`
- Operating system and bit: `5.4.0-33-generic x86_64`

## Description

I need a special format of the `tools/pinyin` output to be:

```
$ pinyin 中国话
ZhongGuoHua
```

Justification: this is mainly to rename Chinese-named files into their pinyin counterparts. Thus

- the space is unwelcome, and because of this
- need capital each letter to easily tell them apart

I.e., two more switches will be needed/added, for space and capitalization. This would be the 99.9% use case *for me* to use this tool. 

I was planning to fork and add the feature on my own, but think I'd better ask first and see if such added output format would be welcome upstream -- I can do all the modification and send in PR myself, if idea accepted.

**Comment by suntong** [comment]
Please consider. I'm still thinking they might be widely needed features. 
If agree, I can start working on it.

**Comment by vcaesar** [comment]
OK, please give me PR.

**Comment by suntong** [comment]
great. will do this weekend. thx.
